global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "bikerent_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "bikerent-rest:8080",
            "notification-service:8082",
            "statistics-service:8083"
          ]